apiVersion: v1
kind: Pod
metadata:
  labels:
    app: newman-run
  name: newman-run
  namespace: integration
spec:
  restartPolicy: Never
  containers:
  - image: gcr.io/betciointegration/newman-run:latest
    name: newman-run
    envFrom:
    - configMapRef:
        name: newman-run
    